### ISSUE TITLE
when i use 

### ISSUE THREAD

**Issue by lmymoonsky** [webpack-contrib/css-minimizer-webpack-plugin#124]
### Actual Behavior
There is no error when running build on centos7.2.
There is no problem running build on a local MAC

Both environment node versions are V12 +

Run failed ,the message like it:

```
 message: 'static/css/styles.febb911f.css from Css Minimizer\n' +
       'Error: [object Object] is not a PostCSS plugin\n' +
       '    at Processor.normalize (workspace/node_modules/postcss/lib/processor.js:168:15)\n' +
       '    at new Processor (workspace/node_modules/postcss/lib/processor.js:52:25)\n' +
       '    at postcss (workspace/node_modules/postcss/lib/postcss.js:55:10)\n' +
       '    at cssnanoPlugin (workspace/node_modules/cssnano/dist/index.js:145:31)\n' +
       '    at cssnanoMinify (eval at transform (workspace/node_modules/css-minimizer-webpack-plugin/dist/minify.js:34:28), :49:33)\n' +
       '    at minify (workspace/node_modules/css-minimizer-webpack-plugin/dist/minify.js:15:32)\n' +
       '    at Object.transform (workspace/node_modules/css-minimizer-webpack-plugin/dist/minify.js:35:24)\n' +
       '    at execFunction (workspace/node_modules/css-minimizer-webpack-plugin/node_modules/jest-worker/build/workers/threadChild.js:158:17)\n' +
       '    at execHelper (workspace/node_modules/css-minimizer-webpack-plugin/node_modules/jest-worker/build/workers/threadChild.js:137:5)\n' +
       '    at execMethod (workspace/node_modules/css-minimizer-webpack-plugin/node_modules/jest-worker/build/workers/threadChild.js:141:5)'
   }
```

**Comment by lmymoonsky** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> Please fill out all fields, I don't know how reproduce this problem, also as you can see problem from `postcss` - `is not a PostCSS plugin`

I'm sorry
I've finished filling in the questions

**Comment by alexander-akait** [comment]
Run `npm ls postcss` and `npm ls cssnano`

**Comment by lmymoonsky** [comment]
Thank you very much

The postcss is not installed online
```
npm ls postcss

 ├─┬ css-loader@6.3.0
 │ └── UNMET PEER DEPENDENCY postcss@8.3.9 
 ├─┬ css-minimizer-webpack-plugin@3.0.0
 │ └── UNMET PEER DEPENDENCY postcss@8.3.9 
```
When I install postcss, it is run successd
