### ISSUE TITLE
Possible regression in v3.1.0 with "Minimizer function doesn't return result"

### ISSUE THREAD

**Issue by cexbrayat** [webpack-contrib/css-minimizer-webpack-plugin#126]
### Actual Behavior

It looks like the recent release of v3.1.0 introduced a possible regression.
I'm not using css-minimizer-webpack-plugin directly, as I am a user of Vue CLI and the CLI handles the webpack config.

### Expected Behavior

The repro with the CLI is [here](https://github.com/cexbrayat/css-mini). I know this is not a minimal reproduction, and I'm sorry. Feel free to close the issue if that's not helpful, but downgrading css-minimizer-webpack-plugin to v3.0.2 instead of v3.1.0 fixes the issue, so I suspect there is a regression somewhere as nothing changed in the Vue CLI configuration.

The CLI uses it internally like this:
https://github.com/vuejs/vue-cli/blob/57926ab3c1fcfde88261df5f2885a2a70637034a/packages/%40vue/cli-service/lib/config/css.js#L220-L231

### How Do We Reproduce?

https://github.com/cexbrayat/css-mini

This is a bare project created with the CLI. This project fails with the error:

```
⠋  Building for production...

 ERROR  Failed to compile with 1 error                                                                                               10:18:52

 error  in css/app.8a97e00d.css

css/app.8a97e00d.css from Css Minimizer Plugin
Error: Minimizer function doesn't return result
    at minify (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/css-minimizer-webpack-plugin/dist/minify.js:29:13)
    at async Object.transform (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/css-minimizer-webpack-plugin/dist/minify.js:62:18)

 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/webpack.js:141:8
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/Cache.js:150:23)
    at /Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/Compiler.js:1156:15
    at Hook.eval [as callAsync] (eval at create (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/Users/ced-pro/Code/test/vue-cli-tests/css-mini/node_modules/webpack/lib/Compiler.js:1149:23)
error Command failed with exit code 1.
```

I opened an issue on the CLI side, but thought that this was maybe a upstream issue, as this is working fine if we force the CLI to use v3.0.2 via a resolution.

See https://github.com/vuejs/vue-cli/issues/6723 for more details

**Comment by alexander-akait** [comment]
Yes, regression, due https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/src/minify.js#L26, we should change it on `typeof minifyResult.code === undefined || typeof minifyResult.code === null`

**Comment by cexbrayat** [comment]
I confirm that it works again, thanks for your quick fix and release!
