### ISSUE TITLE
fix UnhandledPromiseRejectionWarning: DataCloneError: function destructLexErrorInfo()

### ISSUE THREAD

**Issue by the-stas** [webpack-contrib/css-minimizer-webpack-plugin#140]
### Bug report

exception during the build

### Actual Behavior

build fail because of the error
```
(node:2528) UnhandledPromiseRejectionWarning: DataCloneError: function destructLexErrorInfo() {
// remove cyclic references added to error info:           // info....<omitted>... } could not be cloned.  
at reportError (node_modules\jest-worker\build\workers\threadChild.js:100:32) 
at reportClientError (node_modules\jest-worker\build\workers\threadChild.js:84:10)
 (Use `node --trace-warnings ...` to show where the warning was created) (node:2528)
UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function without a catch block,
or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection,
use the CLI flag `--unhandled-rejections=strict`
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
(rejection id: 1) (node:2528) [DEP0018] DeprecationWarning:
Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.
```

### Expected Behavior

build should finish with success

### How Do We Reproduce?

follow the README.MD steps for plugin setup
1) install the npm package
2) modify webpack config per README.MD
3) run npm build command per your package.json file

**Comment by the-stas** [comment]
@alexander-akait please take a look

**Comment by alexander-akait** [comment]
Without reproducible example I can't help, looks like you pass something what can be serialized

**Comment by the-stas** [comment]
seems like it is a duplicate of https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/113
closing the ticket
@alexander-akait BTW, thanks for the quick reaction!
