### ISSUE TITLE
Error: Unexpected '/'. Escaping special characters with \ may help.

### ISSUE THREAD

**Issue by wtlsky** [webpack-contrib/css-minimizer-webpack-plugin#166]
"sass": "^1.50.0"
 "sass-loader": "^12.6.0"

static/css/4790.810b13a6.css from Css Minimizer plugin
Error: Unexpected '/'. Escaping special characters with \ may help.
    at D:\markingCloud\static\css\4790.810b13a6.css:36:1
    at Root._error (D:\markingCloud\node_modules\postcss-selector-parser\dist\parser.js:174:16)  
    at Root.error (D:\markingCloud\node_modules\postcss-selector-parser\dist\selectors\root.js:43:19)
    at Parser.error (D:\markingCloud\node_modules\postcss-selector-parser\dist\parser.js:740:21) 
    at Parser.unexpected (D:\markingCloud\node_modules\postcss-selector-parser\dist\parser.js:759:17)
    at Parser.combinator (D:\markingCloud\node_modules\postcss-selector-parser\dist\parser.js:656:12)
    at Parser.parse (D:\markingCloud\node_modules\postcss-selector-parser\dist\parser.js:1102:14)    at Parser.loop (D:\markingCloud\node_modules\postcss-selector-parser\dist\parser.js:1044:12) 
    at new Parser (D:\markingCloud\node_modules\postcss-selector-parser\dist\parser.js:164:10)   
    at Processor._root (D:\markingCloud\node_modules\postcss-selector-parser\dist\processor.js:53:18)
    at Processor._runSync (D:\markingCloud\node_modules\postcss-selector-parser\dist\processor.js:100:21)

**Comment by alexander-akait** [comment]
Please open an issue in `postcss-selector-parser` and provide code (I will investigate), we can't fix it here, sorry

**Comment by anoop0567** [comment]
Hi, @wtlsky have you found any solution for this issue?
